#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
  path: /login
  controller: App\Infrastructure\Symfony\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Infrastructure\Symfony\Controller\SecurityController::logout

app_register:
  path: /register
  controller: App\Domain\User\UserInterface\Action\RegistrationAction
